### ISSUE TITLE
Add θ and ð phonemes

### ISSUE THREAD

**Issue by trans** [LogosInitiative/logla#2]
Consider adding `θ` and  `ð`, i.e. English's `th` both voiced and unvoiced, to the language. While apparently these are not widely common among many languages, they are not difficult to learn. How hard is it, after all, to put your tongue against your upper teeth and blow? The difficulty is insignificant compared to distinguishing `r` and `l` for Japanese speakers, and pronouncing pure `o` for English speakers.

The advantage of adding these two letters is, of course, the expanded range of words that would be made possible -- dozens of new "cmavo" and thousands of new "gismu". It would also make borrowing some English, German and Arabic words easier.

The downside of adding `θ` and  `ð` is that they sound very much like `f` and `v` respectively. It can be hard to tell the two apart in many cases. Consider "think" vs "fink", "thought" vs "fought" and "that" vs "vat". 

If it is decided that it is best _not_ to add `θ` and  `ð` to the language because of the aforementioned downside, then at least the language could allow `f` and `v` to gain these sounds as acceptable alternate pronunciations.

**Comment by trans** [comment]
Given just how few language seem to have these sound (see http://www.joerg-rhiemeier.de/Conlang/segmental_phonemes.png), I think it is better to go with the allophones, so I submit that this proposal be a consideration of that instead of adding θ and ð as new phonemes outright.

**Comment by thetommoore** [comment]
Like you said, it doesn't seem like it would be hard to explain how to produce these sounds, so is the concern with how few languages use it that they would be difficult to discern?
By that line of reasoning, there needs to be significant restriction added to the phonotactics. For example, Japanese doesn't distinguish /z/ and /dz/.

**Comment by trans** [comment]
I am not too found of /dz/ myself :wink: But I think the concern is the combination --the fact that so few languages have them AND that they sound so much like [f] and [v]. If it were just one or the other than I probably wouldn't hesitate to support adding them as separate phonemes (per my original inclination).

**Comment by thetommoore** [comment]
I'm not sure I agree that labiodental and dental fricatives are that difficult to distinguish. I looked around for some spectrograms, and since I'm not familiar with any centralized collections of these, just found [this](https://www.quora.com/Phonetics/How-does-gender-shift-the-spectrogram-of-phonemes-like-t-and-f) and [this](http://home.cc.umanitoba.ca/~robh/spgs/sol0512.jpg). The key difference, it seems, is that the frequency distribution of [θ] is primarily higher, while [f] is more evenly distributed. It doesn't seem like human hearing should have too much trouble discerning these. If nothing else, there's a massive list of [minimal pairs in English](http://en.wiktionary.org/wiki/Appendix:English_dialect-dependent_homophones#Th-fronting) (in dialects without th-fronting). They're fairly close sounds compared to most, but it's still worth considering.

If not simple dental fricatives, we might consider [their alveolar cousins](http://en.wikipedia.org/wiki/Voiceless_alveolar_fricative#Voiceless_alveolar_non-sibilant_fricative) as the primary allophones.

**Comment by trans** [comment]
There is a distinguishable difference. I don't disagree with that. Anyone who speaks with a th-fronting accent will... well, will have an accent. But it's rather slight one in comparison to others.

There was a quote in the first link you shared that I think is a bit telling:

> But, perceptually, "listeners could identify the sex of the speakers from the isolated  productions of
> /s/ and /∫/, but could not from the /f/ and /θ/  productions"

I was unaware of the two "alveolar cousins", though they sound closer to [ʃ] and [ʒ] to me, and remind me of two other phones: [ɬ](https://en.wikipedia.org/wiki/Voiceless_alveolar_lateral_fricative) and [ɮ](https://en.wikipedia.org/wiki/Voiced_alveolar_lateral_fricative).

I'm not sure. I worry about the "noisy room" problem. On the other hand, perhaps digraphs would work for some of them, e.g /lc/ for [ɬ].

**Comment by thetommoore** [comment]
I personally would realize /lc/ as [ʟʃ], but maybe /ɬ/ and /ɮ/ could be introduced as separate phonemes. It would be nice to have a consistent system of determining what sounds would be easy to distinguish under ambient noise conditions. I'll open separate issues for these.

**Comment by trans** [comment]
That's sort of the idea. A novice could realize it as [ʟʃ] and "graduate" to [ɬ] over time.

**Comment by thetommoore** [comment]
Maybe, but a complex system of allophony would only be an obstacle to beginners.

**Comment by trans** [comment]
Closing this issue in favor of #11.
